name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
      
      - name: Create binary directory
        shell: bash
        run: |
          mkdir -p D:/a/autodeafenplus/autodeafenplus/build/merged
          unzip D:/a/autodeafenplus/autodeafenplus/build/okayscylla.autodeafenplus.geode -d D:/a/autodeafenplus/autodeafenplus/build/merged
          rm D:/a/autodeafenplus/autodeafenplus/build/okayscylla.autodeafenplus.geode
          mkdir -p D:/a/autodeafenplus/autodeafenplus/build/merged/binaries/win
          mv D:/a/autodeafenplus/autodeafenplus/build/merged/resources/okayscylla.autodeafenplus/libzmq.dll D:/a/autodeafenplus/autodeafenplus/build/merged/binaries/win
      
      - name: Compress updated .geode file
        shell: pwsh
        run: |
          Compress-Archive -Path D:\a\autodeafenplus\autodeafenplus\build\merged\* -DestinationPath D:\a\autodeafenplus\autodeafenplus\build\okayscylla.autodeafenplus.geode

      - name: Upload the merged .geode mod file
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/build/okayscylla.autodeafenplus.geode
          archive: false
