name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build-mod:
    name: Build main mod (Windows)
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
      
      - name: Setup binaries directory
        shell: bash
        run: |
          mkdir -p D:/a/autodeafenplus/autodeafenplus/build/merged
          unzip D:/a/autodeafenplus/autodeafenplus/build/okayscylla.autodeafenplus.geode -d D:/a/autodeafenplus/autodeafenplus/build/merged
          rm D:/a/autodeafenplus/autodeafenplus/build/okayscylla.autodeafenplus.geode
          mkdir -p D:/a/autodeafenplus/autodeafenplus/build/merged/binaries/win
          mv D:/a/autodeafenplus/autodeafenplus/build/merged/resources/okayscylla.autodeafenplus/libzmq.dll D:/a/autodeafenplus/autodeafenplus/build/merged/binaries/win

      - name: Compress updated .geode file
        shell: pwsh
        run: |
          Compress-Archive -Path D:\a\autodeafenplus\autodeafenplus\build\merged\* -DestinationPath D:\a\autodeafenplus\autodeafenplus\build\windows.geode

      - name: Upload merged Windows .geode mod file
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}\build\*.geode
          archive: false

  build-bridge:
    name: Build Linux input bridge and upload all built mod files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Download built mod files
        uses: actions/download-artifact@v8
        with:
          path: built
      
      - name: Setup Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Build the bridge
        shell: bash
        run: |
          python -m pip install -r requirements.txt
          python -m pyinstaller --onefile --collect-all --optimize 2 --strip src/bridge.py

      - name: Add bridge to Windows mod file
        shell: bash
        run: |
          mkdir -p resources/okayscylla.autodeafenplus/
          mv dist/bridge resources/okayscylla.autodeafenplus/
          zip -ur built/windows.geode resources
          mkdir -p merged/windows
          mv built/windows.geode merged/windows/okayscylla.autodeafenplus.geode

      - name: Upload all .geode mod files
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/merged/*/*.geode
          archive: false