name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: ${{ matrix.config.target }}
      
      - name: Creating binary directory
        shell: bash
        run: |
        mkdir -p ${{ github.workspace }}/output/merged
        unzip ${{ steps.build.outputs.output }}/okayscylla.autodeafenplus.geode -d ${{ github.workspace }}/output/merged
        rm ${{ steps.build.outputs.output }}/okayscylla.autodeafenplus.geode
        mkdir -p ${{ github.workspace }}/output/merged/binaries/win
        mv ${{ github.workspace }}/output/resources/libzmq.dll ${{ github.workspace }}/output/merged/binaries/win/
        zip -r ${{ steps.build.outputs.output }}/okayscylla.autodeafenplus.geode ${{ github.workspace }}/output/merged/*

      - name: Upload the merged .geode mod file
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.build.outputs.output }}/okayscylla.autodeafenplus.geode
          archive: false
