name: Create GitHub release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Download latest artifact
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Download latest artifact
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download --dir artifacts --name all-platforms.zip
      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          files:
            artifacts/windows/okayscylla.autodeafenplus.geode